language: objective-c
before_install:
  - gem install xcpretty
script:
  - rake "clean[JavaScriptBridge.xcworkspace, 'JavaScriptBridge UICatalog Tests HelloWorld']"
  - rake "build[JavaScriptBridge.xcworkspace, 'JavaScriptBridge UICatalog Tests HelloWorld']"
  - rake "test[JavaScriptBridge.xcworkspace, 'Tests']"
   